"""Code quality scanner: mypy → GitHub issues for missing type annotations."""

import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from datetime import datetime
from pathlib import Path
from typing import Any

ISSUE_BODY = """\
## Missing type annotations

- **File:** `{file_path}`
- **Function:** `{function_name}`
- **Line:** {line_number}

## mypy output
```
{mypy_output}
```

## Acceptance criteria
- [ ] All parameters and return type annotated
- [ ] `mypy --strict {file_path}` reports no errors for this function
- [ ] Full unit test suite passes (`pytest tests/unit_tests`)
- [ ] PR opened against `main` with label `devin-remediated`

## Auto-generated
Generated by `scripts/scan_quality.py` on {timestamp}
"""

# Target directory — rich in utility functions, good mypy coverage
SCAN_TARGETS = [
    "superset/utils/",
    "superset/db_engine_specs/",
]

MAX_ISSUES = 6


def _run_mypy(repo_path: str, target: str) -> list[dict[str, Any]]:
    full_target = Path(repo_path) / target
    if not full_target.exists():
        return []

    result = subprocess.run(
        ["mypy", "--strict", "--ignore-missing-imports", "--output=json", str(full_target)],
        capture_output=True,
        text=True,
        cwd=repo_path,
    )

    findings: list[dict[str, Any]] = []
    for line in result.stdout.splitlines():
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if entry.get("severity") == "error" and "annotation" in entry.get("message", "").lower():
            findings.append(entry)
    return findings


def _run_mypy_text(repo_path: str, target: str) -> list[str]:
    """Fallback: parse text mypy output for 'no type annotation' errors."""
    full_target = Path(repo_path) / target
    if not full_target.exists():
        return []

    result = subprocess.run(
        ["mypy", "--strict", "--ignore-missing-imports", str(full_target)],
        capture_output=True,
        text=True,
        cwd=repo_path,
    )

    pattern = re.compile(r"(.+):(\d+): error: (.+)")
    findings = []
    for line in result.stdout.splitlines():
        m = pattern.match(line)
        if m and any(kw in m.group(3) for kw in ["annotation", "return type", "type ignore"]):
            findings.append({
                "file": m.group(1),
                "line": m.group(2),
                "message": m.group(3),
                "raw_line": line,
            })
    return findings


def _extract_function_name(file_path: str, line_number: int) -> str:
    try:
        lines = Path(file_path).read_text().splitlines()
        # Search backwards from error line for `def` keyword
        for i in range(min(line_number - 1, len(lines) - 1), max(0, line_number - 10), -1):
            m = re.match(r"\s*(?:async\s+)?def\s+(\w+)", lines[i])
            if m:
                return m.group(1)
    except Exception:
        pass
    return "<unknown>"


def run(repo_path: str = ".", dry_run: bool = False) -> list[dict[str, Any]]:
    from app.config import settings
    from app.github_client import GitHubClient

    gh = GitHubClient(settings.github_token, settings.github_owner, settings.github_repo)

    for name, color, desc in [
        ("devin-remediate", "d93f0b", "Trigger auto-remediation"),
        ("playbook:type-hints", "1d76db", "Type hints playbook"),
        ("auto-generated", "e4e669", "Created by scanner"),
    ]:
        gh.ensure_label(name, color, desc)

    all_findings: list[dict[str, Any]] = []
    for target in SCAN_TARGETS:
        text_findings = _run_mypy_text(repo_path, target)
        all_findings.extend(text_findings)
        if len(all_findings) >= MAX_ISSUES:
            break

    # Deduplicate by file+line
    seen: set[str] = set()
    unique: list[dict[str, Any]] = []
    for f in all_findings:
        key = f"{f['file']}:{f['line']}"
        if key not in seen:
            seen.add(key)
            unique.append(f)
        if len(unique) >= MAX_ISSUES:
            break

    created: list[dict] = []
    for finding in unique:
        rel_file = finding["file"].replace(str(Path(repo_path)) + "/", "")
        line_num = int(finding["line"])
        func_name = _extract_function_name(finding["file"], line_num)

        body = ISSUE_BODY.format(
            file_path=rel_file,
            function_name=func_name,
            line_number=line_num,
            mypy_output=finding["raw_line"],
            timestamp=datetime.utcnow().isoformat(),
        )
        title = f"[type-hints] Add annotations to {func_name}() in {rel_file}"
        labels = ["devin-remediate", "playbook:type-hints", "auto-generated"]

        if dry_run:
            print(f"[DRY RUN] Would create: {title}")
            created.append({"title": title})
            continue

        issue = gh.create_issue(title, body, labels)
        created.append(issue)
        print(f"Created issue #{issue['number']}: {title}")

    return created


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-path", default=".", help="Path to superset fork")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    run(args.repo_path, args.dry_run)
