"""CVE scanner: OSV API → curated GitHub issues."""

import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))

import httpx

OSV_API = "https://api.osv.dev/v1/query"
NVD_LINK = "https://nvd.nist.gov/vuln/detail/{cve_id}"
MIN_SEVERITY = {"MODERATE", "HIGH", "CRITICAL"}

ISSUE_BODY = """\
## Vulnerability
- **Package:** `{package}`
- **Current version:** `{current_version}`
- **Fix version:** `{fix_version}`
- **CVE:** [{cve_id}]({nvd_link})
- **Severity:** {severity}
- **CVSS:** {cvss}

## Affected files
{affected_files}

## Acceptance criteria
- [ ] Package bumped in all requirements files
- [ ] `pip-audit` no longer reports this CVE
- [ ] Full unit test suite passes (`pytest tests/unit_tests`)
- [ ] No new test failures introduced
- [ ] No tests skipped via `@pytest.mark.skip`
- [ ] PR opened against `main` with label `devin-remediated`

## Changelog
{changelog}

## Auto-generated
Generated by `scripts/scan_cves.py` on {timestamp}
"""


_PIN_RE = re.compile(r'^([A-Za-z0-9_\-\.]+)==([^\s;#]+)')


def _parse_req_files(req_files: list[Path]) -> list[tuple[str, str]]:
    seen: set[tuple[str, str]] = set()
    packages: list[tuple[str, str]] = []
    for f in req_files:
        for line in f.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith('#') or line.startswith('-'):
                continue
            m = _PIN_RE.match(line)
            if m:
                key = (m.group(1).lower().replace('-', '_'), m.group(2))
                if key not in seen:
                    seen.add(key)
                    packages.append((m.group(1), m.group(2)))
    return packages


def _run_pip_audit(repo_path: str) -> list[dict[str, Any]]:
    req_files = list(Path(repo_path).glob("requirements/*.txt"))
    if not req_files:
        print("No requirements files found", file=sys.stderr)
        return []

    packages = _parse_req_files(req_files)
    print(f"Scanning {len(packages)} pinned packages via OSV…", file=sys.stderr)

    vulns: list[dict[str, Any]] = []
    seen_vulns: set[tuple[str, str]] = set()

    for package, version in packages:
        try:
            resp = httpx.post(
                OSV_API,
                json={"version": version, "package": {"name": package, "ecosystem": "PyPI"}},
                timeout=10,
            )
            resp.raise_for_status()
            osv_vulns = resp.json().get("vulns", [])
        except Exception:
            continue

        for v in osv_vulns:
            key = (package.lower(), v["id"])
            if key in seen_vulns:
                continue
            seen_vulns.add(key)

            fix_versions = [
                event["fixed"]
                for affected in v.get("affected", [])
                for r in affected.get("ranges", [])
                for event in r.get("events", [])
                if "fixed" in event
            ]
            if not fix_versions:
                continue
            vulns.append({
                "package": package,
                "current_version": version,
                "fix_version": fix_versions[-1],
                "vuln_id": v["id"],
                "aliases": v.get("aliases", []),
                "description": v.get("summary", ""),
            })
    return vulns


def _query_osv(package: str, version: str) -> dict[str, Any]:
    try:
        resp = httpx.post(
            OSV_API,
            json={"version": version, "package": {"name": package, "ecosystem": "PyPI"}},
            timeout=10,
        )
        resp.raise_for_status()
        vulns = resp.json().get("vulns", [])
        return vulns[0] if vulns else {}
    except Exception:
        return {}


def _extract_cve(aliases: list[str]) -> str:
    for a in aliases:
        if a.startswith("CVE-"):
            return a
    return aliases[0] if aliases else "UNKNOWN"


def _severity_from_osv(osv_data: dict) -> tuple[str, float]:
    for sev in osv_data.get("severity", []):
        score_str = sev.get("score", "")
        # CVSS score is typically "CVSS:3.1/AV:N/..." — extract the numeric score
        if "CVSS:3" in score_str:
            parts = score_str.split("/")
            try:
                score = float(parts[-1].split(":")[-1])
            except (ValueError, IndexError):
                score = 0.0
            if score >= 9.0:
                return "CRITICAL", score
            elif score >= 7.0:
                return "HIGH", score
            elif score >= 4.0:
                return "MODERATE", score
    return "MODERATE", 0.0


def _find_affected_req_files(repo_path: str, package: str) -> list[str]:
    lines = []
    for f in Path(repo_path).glob("requirements/*.txt"):
        content = f.read_text()
        for i, line in enumerate(content.splitlines(), 1):
            if package.lower() in line.lower() and not line.startswith("#"):
                lines.append(f"- `{f.relative_to(repo_path)}` (line {i})")
    return lines


def run(repo_path: str = ".", dry_run: bool = False, max_issues: int = 10) -> list[dict[str, Any]]:
    from app.config import settings
    from app.github_client import GitHubClient

    gh = GitHubClient(settings.github_token, settings.github_owner, settings.github_repo)

    # Ensure labels exist
    for name, color, desc in [
        ("devin-remediate", "d93f0b", "Trigger auto-remediation"),
        ("playbook:dep-upgrade", "0075ca", "Dependency upgrade playbook"),
        ("auto-generated", "e4e669", "Created by scanner"),
    ]:
        gh.ensure_label(name, color, desc)

    raw_vulns = _run_pip_audit(repo_path)
    created: list[dict] = []

    # Deduplicate by (package, cve_id) — same CVE can appear from multiple req files
    seen: set[tuple[str, str]] = set()

    for v in raw_vulns:
        if len(created) >= max_issues:
            break

        cve_id = _extract_cve(v["aliases"])
        dedup_key = (v["package"].lower(), cve_id)
        if dedup_key in seen:
            continue
        seen.add(dedup_key)

        osv = _query_osv(v["package"], v["current_version"])
        severity, cvss = _severity_from_osv(osv)

        if severity not in MIN_SEVERITY:
            continue

        affected = _find_affected_req_files(repo_path, v["package"])
        affected_str = "\n".join(affected) if affected else "- requirements files"

        body = ISSUE_BODY.format(
            package=v["package"],
            current_version=v["current_version"],
            fix_version=v["fix_version"],
            cve_id=cve_id,
            nvd_link=NVD_LINK.format(cve_id=cve_id),
            severity=severity,
            cvss=cvss or "N/A",
            affected_files=affected_str,
            changelog=f"See https://pypi.org/project/{v['package']}/#history",
            timestamp=datetime.now(timezone.utc).isoformat(),
        )

        title = f"[CVE] Bump {v['package']} {v['current_version']} → {v['fix_version']} ({cve_id})"
        labels = ["devin-remediate", "playbook:dep-upgrade", f"severity:{severity.lower()}", "auto-generated"]

        if dry_run:
            print(f"[DRY RUN] Would create issue: {title}")
            created.append({"title": title, "body": body})
            continue

        issue = gh.create_issue(title, body, labels)
        created.append(issue)
        print(f"Created issue #{issue['number']}: {title}")

    return created


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-path", default=".", help="Path to superset fork")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--max-issues", type=int, default=10)
    args = parser.parse_args()
    run(args.repo_path, args.dry_run, args.max_issues)
